---
name: Stylua
on:
  workflow_dispatch: ~
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Format project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Format project
        uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          args: --check .
