---
name: Stylua
on:
  pull_request:
    paths:
      - 'lua/**'
      - 'after/**'
      - 'ftplugin/**'
  push:

jobs:
  stylua:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.19
          # CLI arguments
          args: --check .
